name: Xbox Price Checker

on: [push]

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Read.
        run: |
          cookie="has_adblock=0; EU_COOKIE_LAW_CONSENT=true; currency_13=RUB; language_13=ru; giftcardAllowed_4=0; adblock_check_count=4; support_us_count=4;"

          regexPrice='Начиная с<\/span> <span class="pprice ">([0-9.]+)<\/span> (.{0,4}) <\/div>'
          regexCountry='<img src="\/assets\/img\/flag\/[a-zA-Z-]+.png" alt="([a-zA-Z-]+)" width="16" height="16" \/>'

          while read gameId; do
            curl --cookie "${cookie}" https://xbox-store-checker.com/ru/game/compare/a/${gameId} > ${gameId}.txt
            echo "$gameId"
            if [[ $(cat ${gameId}.txt) =~ $regexPrice ]]
            then
                price="${BASH_REMATCH[1]}"
                currency="${BASH_REMATCH[2]}"
            fi
            if [[ $(cat ${gameId}.txt) =~ $regexCountry ]]
            then
                country="${BASH_REMATCH[1]}"
            fi
            echo "${price} ${currency} ${country}"
          done <ids.txt
