name: Xbox Price Checker

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight.
  push:
    paths-ignore:
      - '**.md'

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Read.
        run: |
          echo "| ID | Name | Checker URL | Xbox URL | Price | Real Price | Discount | Ends in | Original Cur | Country |" > table.md
          echo "|-|-|-|-|-|-|-|-|-|-|" >> table.md

          cookie="has_adblock=0; EU_COOKIE_LAW_CONSENT=true; currency_13=RUB; language_13=ru; giftcardAllowed_4=0; adblock_check_count=4; support_us_count=4;"

          userAgent='User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15'

          regexPrice='Начиная с<\/span> <span class="pprice ">([0-9.]+)<\/span> (.{0,4}) <\/div>'
          regexCountry='<img src="\/assets\/img\/flag\/[a-zA-Z-]+.png" alt="([a-zA-Z-]+)" width="16" height="16" \/>'
          regexNameYear='<h2 class="game-title">(.+)<\/h2> <span class="game-date">(\([0-9]+\))<\/span>'
          regexDiscount='<span class="badge badge-success">Discount : -([0-9]+)%<\/span>'
          regexOriginalCurrency='pprice price-not-convert-base">([0-9]+)<\/span> .+ (\([a-zA-Z]+\))'

          while read gameId; do
            curl \
              --cookie "${cookie}" \
              -H "${userAgent}" \
              -H 'Accept-Language: ru-RU,ru;q=0.9' \
              https://xbox-store-checker.com/ru/game/compare/a/${gameId} > ${gameId}.txt

            apiJsonRoot="['Products'][0]['DisplaySkuAvailabilities'][0]['Availabilities'][0]"
            apiJsonPrice="${apiJsonRoot}['OrderManagementData']['Price']"
            apiJsonConditions="${apiJsonRoot}['Conditions']['EndDate']"
            apiResponse=$(curl \
              -X POST \
              -d "productIds=${gameId}" \
              https://storeedgefd.dsx.mp.microsoft.com/v8.0/sdk/products\?market\=AR\&locale\=es-AR\&deviceFamily\=Windows.Desktop)
            originalCurPrice=$(echo "${apiResponse}" \
            | python3 -c "import sys, json; print(json.load(sys.stdin)${apiJsonPrice}['ListPrice'])")
            originalCur=$(echo "${apiResponse}" \
            | python3 -c "import sys, json; print(json.load(sys.stdin)${apiJsonPrice}['CurrencyCode'])")
            priceDiscountEnds=$(echo "${apiResponse}" \
            | python3 -c "import sys, json; out=str(json.load(sys.stdin)${apiJsonConditions}); print('' if out.startswith('999') else out)")

            echo "$gameId"
            if [[ $(cat ${gameId}.txt) =~ $regexPrice ]]
            then
                price="${BASH_REMATCH[1]}"
                currency="${BASH_REMATCH[2]}"
            fi
            if [[ $(cat ${gameId}.txt) =~ $regexCountry ]]
            then
                country="${BASH_REMATCH[1]}"
            fi
            if [[ $(cat ${gameId}.txt) =~ $regexNameYear ]]
            then
                gameName="${BASH_REMATCH[1]}"
                gameYear="${BASH_REMATCH[2]}"
            fi
            if [[ $(cat ${gameId}.txt) =~ $regexDiscount ]]
            then
                priceDiscount=" **–${BASH_REMATCH[1]}%**"
            else
                priceDiscount=""
            fi
            echo "${price} ${currency} ${country}"

            checkerURL="https://xbox-store-checker.com/en/game/compare/a/${gameId}"
            xboxURL="https://www.xbox.com/ru-RU/games/store/a/${gameId}"
            multiplier="1.7"
            realPrice=$(bc -l <<<"${price}*${multiplier}")

            echo "| ${gameId} \
            | ${gameName} ${gameYear} \
            | [URL](${checkerURL}) \
            | [URL](${xboxURL}) \
            | ${price} ${currency} \
            | ${realPrice} ${currency} \
            | ${priceDiscount} \
            | ${priceDiscountEnds} \
            | ${originalCur} ${originalCurPrice} \
            | ${country} \
            |" >> table.md
          done <ids.txt

      - name: Commit files.
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add table.md
          git commit -a -m "Updated table on $(date)"
      - name: Push changes.
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

